# Generated by Django 3.1.6 on 2021-03-02 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='User ID')),
                ('name', models.TextField(max_length=512, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('email', models.EmailField(max_length=1000, verbose_name='Email')),
                ('amount', models.FloatField(verbose_name='Max Amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EthereumCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('balance', models.FloatField(max_length=1000000000, verbose_name='Bitcoin Wallet Balance')),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ethereum_currency', to='users.useraccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BitcoinCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('balance', models.FloatField(max_length=1000000000, verbose_name='Bitcoin Wallet Balance')),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitcoin_currency', to='users.useraccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
